version: '3.2'

services:
    config_traefik:
        build: 
            context: ./configs
            dockerfile: traefik.dockerfile
        stdin_open: true
        volumes:
            - type: volume
              source: config_traefik
              target: "/etc/traefik"
    watchtower:
        image: v2tec/watchtower
        container_name: "caesarapp-watchtower"
        command: --cleanup --label-enable --interval 300
        labels:
            - "traefik.enable=false"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    traefik:
        image: traefik:1.6.2-alpine # The official Traefik docker image
        command: --web --docker # Enables the web UI and tells Træfik to listen to docker
        networks:
            - frontend
            - backend
        ports:
            - "80:80"     # The HTTP port
        depends_on:
            - config_traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - 'config_traefik:/etc/traefik/'
        labels:                                                                                                                 
            - traefik.port=8080                                                                                                                                                                       
    client:
        image: 4xxi/caesarapp-web-client
        depends_on:
            - php
        networks:
            - frontend  
        labels:
            - "traefik.enable=true"
            - "traefik.backend=client"
            - "traefik.domain=${DOMAIN}"
            - "traefik.frontend.rule=Host:${CLIENT_HOSTNAME}"
            - "traefik.frontend.entryPoints=http,https"
            - "com.centurylinklabs.watchtower.enable=true"
        environment:
            SERVER_HTTP_PORT: "${SERVER_HTTP_PORT}"
            SERVER_HOSTNAME: "${SERVER_HOSTNAME}"
            CLIENT_HTTP_PORT: "${CLIENT_HTTP_PORT}"
            CLIENT_HOSTNAME : "${CLIENT_HOSTNAME}"
            BASE_URL: "${BASE_URL}"
            BASE_API_URL: "${BASE_API_URL}"
    php:
        image: 4xxi/caesarapp-server:latest
        depends_on:
            - redis
        volumes:
            - type: volume
              source: code
              target: "/var/www/html"
        expose:
            - "9000"
        entrypoint: ./config/docker/docker-entrypoint.sh
        environment:
            - APP_ENV=${ENV}  
            - REDIS_HOST=redis
            - CORS_ALLOW_ORIGIN=${CLIENT_HOSTNAME}
            - REDIS_PORT=${REDIS_PORT}
        labels:
            - "traefik.enable=false"
            - "com.centurylinklabs.watchtower.enable=true"
        networks: 
            - backend  
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        volumes:
            - type: volume
              source: code
              target: "/var/www/html"
            - 'logs:/var/log/nginx'
        networks: 
            - backend     
        labels:
            - "traefik.domain=${DOMAIN}"
            - "traefik.frontend.rule=Host:${SERVER_HOSTNAME}"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.enable=true"             
    redis:
        image: 'redis:alpine'
        environment:
          - REDIS_PORT=${REDIS_PORT}
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        networks: 
          - backend    
        volumes:
          - 'redis:/etc/redis/database/caesarapp'
        labels: 
            - "traefik.enable=false"  
networks: 
    backend:
    frontend:
volumes:
    redis:
    code: {}
    config_traefik: {}
    logs: {}
    db: {}